// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wynuikchkjlbfeufwbol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5bnVpa2Noa2psYmZldWZ3Ym9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMTAxMjgsImV4cCI6MjA1NTc4NjEyOH0.-Wux3i0N17xKrAW75PbmS1_KlmZ5vgXLXGsSWMH2KHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);